using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;

public static class PhoneDefines
{
	public static List<Track> FillTracks() 
	{
		List<Track> tracks = new List<Track>();
		
		for (int i=0; i<9; i++)
			tracks.Add(new Track());
		
		tracks[0].par.maxvel = 75.0f;
		tracks[0].par.maxacc = 0f;
		tracks[1].par.maxvel = 30.0f;
		tracks[1].par.maxacc = 0f;
		tracks[2].par.maxvel = 45.0f;
		tracks[2].par.maxacc = 0f;
		tracks[3].par.maxvel = 20.0f;
		tracks[3].par.maxacc = 0f;
		tracks[4].par.maxvel = 50.0f;
		tracks[4].par.maxacc = 0f;
		tracks[5].par.maxvel = 25.0f;
		tracks[5].par.maxacc = 0f;
		tracks[6].par.maxvel = 50.0f;
		tracks[6].par.maxacc = 0f;
		tracks[7].par.maxvel = 50.0f;
		tracks[7].par.maxacc = 0f;
		tracks[8].par.maxvel = 50.0f;
		tracks[8].par.maxacc = 0f;
	
		tracks[4].par.defs.Add("B", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["B"].targets.Add((float)-40.0, (float)1.01);
		tracks[4].par.defs["B"].targets.Add((float)20.0, (float)1.02);
		tracks[8].par.defs.Add("B", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["B"].targets.Add((float)-50.0, (float)0.05);
		tracks[0].par.defs.Add("D", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["D"].targets.Add((float)-70.0, (float)0.16);
		tracks[2].par.defs.Add("D", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["D"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("D", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["D"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("D", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["D"].targets.Add((float)-50.0, (float)1.66);
		tracks[6].par.defs.Add("D", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["D"].targets.Add((float)0.0, (float)0.50);
		tracks[0].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["uh"].targets.Add((float)-70.0, (float)0.26);
		tracks[2].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["uh"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["uh"].targets.Add((float)-50.0, (float)0.07);
		tracks[4].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["uh"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["uh"].targets.Add((float)0.0, (float)0.02);
		tracks[6].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["uh"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["uh"].targets.Add((float)-60.0, (float)0.82);
		tracks[8].par.defs.Add("uh", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["uh"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ex"].targets.Add((float)-70.0, (float)0.25);
		tracks[2].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ex"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ex"].targets.Add((float)-80.0, (float)0.00);
		tracks[4].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ex"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ex"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ex"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ex"].targets.Add((float)-50.0, (float)0.73);
		tracks[8].par.defs.Add("ex", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ex"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ey"].targets.Add((float)-70.0, (float)0.20);
		tracks[0].par.defs["ey"].targets.Add((float)0.0, (float)0.12);
		tracks[2].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ey"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ey"].targets.Add((float)-60.0, (float)0.02);
		tracks[4].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ey"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ey"].targets.Add((float)0.0, (float)0.02);
		tracks[6].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ey"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ey"].targets.Add((float)-60.0, (float)0.87);
		tracks[7].par.defs["ey"].targets.Add((float)0.0, (float)0.80);
		tracks[8].par.defs.Add("ey", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ey"].targets.Add((float)-50.0, (float)0.00);
		tracks[2].par.defs.Add("F", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["F"].targets.Add((float)-50.0, (float)1.00);
		tracks[2].par.defs["F"].targets.Add((float)0.0, (float)1.00);
		tracks[4].par.defs.Add("F", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["F"].targets.Add((float)-20.0, (float)0.00);
		tracks[8].par.defs.Add("F", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["F"].targets.Add((float)-20.0, (float)0.00);
		tracks[2].par.defs.Add("G", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["G"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("G", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["G"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("G", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["G"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["fr"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["fr"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["fr"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["fr"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["fr"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["fr"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["fr"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("fr", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["fr"].targets.Add((float)0.0, (float)0.00);
		tracks[2].par.defs.Add("K", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["K"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("K", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["K"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("K", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["K"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("L", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["L"].targets.Add((float)-70.0, (float)0.16);
		tracks[2].par.defs.Add("L", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["L"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("L", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["L"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("L", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["L"].targets.Add((float)-50.0, (float)1.66);
		tracks[6].par.defs.Add("L", new LipSyncData.PhoneDefine());

		tracks[4].par.defs.Add("M", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["M"].targets.Add((float)-40.0, (float)1.01);
		tracks[4].par.defs["M"].targets.Add((float)20.0, (float)1.02);
		tracks[8].par.defs.Add("M", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["M"].targets.Add((float)-50.0, (float)0.05);
		tracks[0].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["hf"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["hf"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["hf"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["hf"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["hf"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["hf"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["hf"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("hf", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["hf"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ae"].targets.Add((float)-70.0, (float)0.26);
		tracks[2].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ae"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ae"].targets.Add((float)-50.0, (float)0.07);
		tracks[4].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ae"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ae"].targets.Add((float)0.0, (float)0.02);
		tracks[6].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ae"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ae"].targets.Add((float)-60.0, (float)0.82);
		tracks[8].par.defs.Add("ae", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ae"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("N", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["N"].targets.Add((float)-70.0, (float)0.16);
		tracks[2].par.defs.Add("N", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["N"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("N", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["N"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("N", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["N"].targets.Add((float)-50.0, (float)1.66);
		tracks[6].par.defs.Add("N", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["N"].targets.Add((float)0.0, (float)0.50);
		tracks[0].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ur"].targets.Add((float)-70.0, (float)0.35);
		tracks[2].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ur"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ur"].targets.Add((float)-50.0, (float)0.37);
		tracks[4].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ur"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ur"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ur"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ur"].targets.Add((float)-50.0, (float)0.80);
		tracks[8].par.defs.Add("ur", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ur"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["oh"].targets.Add((float)-70.0, (float)0.25);
		tracks[2].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["oh"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["oh"].targets.Add((float)-70.0, (float)0.30);
		tracks[4].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["oh"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["oh"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["oh"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["oh"].targets.Add((float)-30.0, (float)0.75);
		tracks[8].par.defs.Add("oh", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["oh"].targets.Add((float)-50.0, (float)0.00);
		tracks[4].par.defs.Add("P", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["P"].targets.Add((float)-40.0, (float)1.01);
		tracks[4].par.defs["P"].targets.Add((float)20.0, (float)1.02);
		tracks[8].par.defs.Add("P", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["P"].targets.Add((float)-50.0, (float)0.05);
		tracks[2].par.defs.Add("hh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["hh"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("hh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["hh"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("hh", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["hh"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ah"].targets.Add((float)-70.0, (float)0.26);
		tracks[2].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ah"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ah"].targets.Add((float)-50.0, (float)0.07);
		tracks[4].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ah"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ah"].targets.Add((float)0.0, (float)0.02);
		tracks[6].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ah"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ah"].targets.Add((float)-60.0, (float)0.82);
		tracks[8].par.defs.Add("ah", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ah"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("R", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["R"].targets.Add((float)-70.0, (float)0.16);
		tracks[2].par.defs.Add("R", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["R"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("R", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["R"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("R", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["R"].targets.Add((float)-50.0, (float)1.66);
		tracks[6].par.defs.Add("R", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["R"].targets.Add((float)0.0, (float)0.50);
		tracks[0].par.defs.Add("S", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["S"].targets.Add((float)-70.0, (float)0.07);
		tracks[2].par.defs.Add("S", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["S"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("S", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["S"].targets.Add((float)-10.0, (float)0.00);
		tracks[5].par.defs.Add("S", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["S"].targets.Add((float)-50.0, (float)0.50);
		tracks[6].par.defs.Add("S", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["S"].targets.Add((float)0.0, (float)0.50);
		tracks[0].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["uw"].targets.Add((float)-70.0, (float)0.35);
		tracks[2].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["uw"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["uw"].targets.Add((float)-50.0, (float)0.37);
		tracks[4].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["uw"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["uw"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["uw"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["uw"].targets.Add((float)-50.0, (float)0.80);
		tracks[8].par.defs.Add("uw", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["uw"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("T", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["T"].targets.Add((float)-70.0, (float)0.16);
		tracks[2].par.defs.Add("T", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["T"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("T", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["T"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("T", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["T"].targets.Add((float)-50.0, (float)1.66);
		tracks[6].par.defs.Add("T", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["T"].targets.Add((float)0.0, (float)0.50);
		tracks[2].par.defs.Add("V", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["V"].targets.Add((float)-50.0, (float)1.00);
		tracks[2].par.defs["V"].targets.Add((float)0.0, (float)1.00);
		tracks[4].par.defs.Add("V", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["V"].targets.Add((float)-20.0, (float)0.00);
		tracks[8].par.defs.Add("V", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["V"].targets.Add((float)-20.0, (float)0.00);
		tracks[2].par.defs.Add("nx", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["nx"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("nx", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["nx"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("nx", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["nx"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["W"].targets.Add((float)-70.0, (float)0.25);
		tracks[2].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["W"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["W"].targets.Add((float)-50.0, (float)0.51);
		tracks[4].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["W"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["W"].targets.Add((float)-50.0, (float)0.00);
		tracks[6].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["W"].targets.Add((float)0.0, (float)0.50);
		tracks[8].par.defs.Add("W", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["W"].targets.Add((float)-60.0, (float)0.12);
		tracks[0].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ao"].targets.Add((float)-70.0, (float)0.35);
		tracks[2].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ao"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ao"].targets.Add((float)-50.0, (float)0.37);
		tracks[4].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ao"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ao"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ao"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ao"].targets.Add((float)-50.0, (float)0.80);
		tracks[8].par.defs.Add("ao", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ao"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ih"].targets.Add((float)-70.0, (float)0.14);
		tracks[2].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ih"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ih"].targets.Add((float)-60.0, (float)0.05);
		tracks[4].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ih"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ih"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ih"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ih"].targets.Add((float)-60.0, (float)0.84);
		tracks[8].par.defs.Add("ih", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ih"].targets.Add((float)-50.0, (float)0.16);
		tracks[0].par.defs.Add("Y", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["Y"].targets.Add((float)-60.0, (float)0.14);
		tracks[2].par.defs.Add("Y", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["Y"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("Y", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["Y"].targets.Add((float)-40.0, (float)0.16);
		tracks[4].par.defs.Add("Y", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["Y"].targets.Add((float)-20.0, (float)0.02);
		tracks[7].par.defs.Add("Y", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["Y"].targets.Add((float)-50.0, (float)0.96);
		tracks[8].par.defs.Add("Y", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["Y"].targets.Add((float)-50.0, (float)0.30);
		tracks[0].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["hr"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["hr"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["hr"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["hr"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["hr"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["hr"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["hr"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("hr", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["hr"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["aq"].targets.Add((float)-60.0, (float)0.30);
		tracks[2].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["aq"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["aq"].targets.Add((float)-80.0, (float)0.00);
		tracks[4].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["aq"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["aq"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["aq"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["aq"].targets.Add((float)-50.0, (float)0.68);
		tracks[8].par.defs.Add("aq", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["aq"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("Z", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["Z"].targets.Add((float)-70.0, (float)0.07);
		tracks[2].par.defs.Add("Z", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["Z"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("Z", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["Z"].targets.Add((float)-10.0, (float)0.00);
		tracks[5].par.defs.Add("Z", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["Z"].targets.Add((float)-50.0, (float)0.50);
		tracks[6].par.defs.Add("Z", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["Z"].targets.Add((float)0.0, (float)0.50);
		tracks[0].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ar"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ar"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ar"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ar"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ar"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ar"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ar"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("ar", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ar"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ow"].targets.Add((float)-70.0, (float)0.26);
		tracks[0].par.defs["ow"].targets.Add((float)-10.0, (float)0.21);
		tracks[2].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ow"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ow"].targets.Add((float)-70.0, (float)0.16);
		tracks[3].par.defs["ow"].targets.Add((float)0.0, (float)0.37);
		tracks[4].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ow"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ow"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ow"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ow"].targets.Add((float)-60.0, (float)0.66);
		tracks[8].par.defs.Add("ow", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ow"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["aw"].targets.Add((float)-70.0, (float)0.35);
		tracks[0].par.defs["aw"].targets.Add((float)0.0, (float)0.30);
		tracks[2].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["aw"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["aw"].targets.Add((float)-70.0, (float)0.07);
		tracks[3].par.defs["aw"].targets.Add((float)0.0, (float)0.44);
		tracks[4].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["aw"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["aw"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["aw"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["aw"].targets.Add((float)-50.0, (float)0.82);
		tracks[8].par.defs.Add("aw", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["aw"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["oy"].targets.Add((float)-70.0, (float)0.25);
		tracks[2].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["oy"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["oy"].targets.Add((float)-80.0, (float)0.00);
		tracks[4].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["oy"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["oy"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["oy"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["oy"].targets.Add((float)-60.0, (float)0.75);
		tracks[8].par.defs.Add("oy", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["oy"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["!"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["!"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["!"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["!"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["!"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["!"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["!"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("!", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["!"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ax"].targets.Add((float)-70.0, (float)0.26);
		tracks[2].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ax"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ax"].targets.Add((float)-50.0, (float)0.07);
		tracks[4].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ax"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ax"].targets.Add((float)0.0, (float)0.02);
		tracks[6].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ax"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ax"].targets.Add((float)-60.0, (float)0.82);
		tracks[8].par.defs.Add("ax", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ax"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ay"].targets.Add((float)-70.0, (float)0.28);
		tracks[0].par.defs["ay"].targets.Add((float)0.0, (float)0.18);
		tracks[2].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ay"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ay"].targets.Add((float)-80.0, (float)0.00);
		tracks[4].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ay"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ay"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ay"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ay"].targets.Add((float)-60.0, (float)0.66);
		tracks[7].par.defs["ay"].targets.Add((float)0.0, (float)0.80);
		tracks[8].par.defs.Add("ay", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ay"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("jh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["jh"].targets.Add((float)-60.0, (float)0.14);
		tracks[2].par.defs.Add("jh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["jh"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("jh", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["jh"].targets.Add((float)-40.0, (float)0.16);
		tracks[4].par.defs.Add("jh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["jh"].targets.Add((float)-20.0, (float)0.02);
		tracks[7].par.defs.Add("jh", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["jh"].targets.Add((float)-50.0, (float)0.96);
		tracks[8].par.defs.Add("jh", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["jh"].targets.Add((float)-50.0, (float)0.30);
		tracks[0].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ir"].targets.Add((float)-70.0, (float)0.30);
		tracks[2].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ir"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ir"].targets.Add((float)-60.0, (float)0.19);
		tracks[4].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ir"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["ir"].targets.Add((float)-20.0, (float)0.66);
		tracks[6].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["ir"].targets.Add((float)0.0, (float)0.00);
		tracks[7].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ir"].targets.Add((float)-50.0, (float)0.73);
		tracks[8].par.defs.Add("ir", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ir"].targets.Add((float)-60.0, (float)0.14);
		tracks[0].par.defs.Add("ch", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["ch"].targets.Add((float)-60.0, (float)0.14);
		tracks[2].par.defs.Add("ch", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["ch"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("ch", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["ch"].targets.Add((float)-40.0, (float)0.16);
		tracks[4].par.defs.Add("ch", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["ch"].targets.Add((float)-20.0, (float)0.02);
		tracks[7].par.defs.Add("ch", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["ch"].targets.Add((float)-50.0, (float)0.96);
		tracks[8].par.defs.Add("ch", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["ch"].targets.Add((float)-50.0, (float)0.30);
		tracks[0].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["iy"].targets.Add((float)-70.0, (float)0.12);
		tracks[2].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["iy"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["iy"].targets.Add((float)-80.0, (float)0.00);
		tracks[4].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["iy"].targets.Add((float)0.0, (float)0.00);
		tracks[5].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["iy"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["iy"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["iy"].targets.Add((float)-50.0, (float)0.96);
		tracks[8].par.defs.Add("iy", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["iy"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[0].par.defs[", (float)"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[2].par.defs[", (float)"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[3].par.defs[", (float)"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[4].par.defs[", (float)"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[5].par.defs[", (float)"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[6].par.defs[", (float)"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[7].par.defs[", (float)"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add(", (float)", new LipSyncData.PhoneDefine());
		tracks[8].par.defs[", (float)"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("dh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["dh"].targets.Add((float)-70.0, (float)0.21);
		tracks[2].par.defs.Add("dh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["dh"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("dh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["dh"].targets.Add((float)-30.0, (float)0.00);
		tracks[5].par.defs.Add("dh", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["dh"].targets.Add((float)-60.0, (float)1.01);
		tracks[5].par.defs["dh"].targets.Add((float)0.0, (float)1.01);
		tracks[6].par.defs.Add("dh", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["dh"].targets.Add((float)-50.0, (float)0.70);
		tracks[0].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["."].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["."].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["."].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["."].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["."].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["."].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["."].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add(".", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["."].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["sil"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["sil"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["sil"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["sil"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["sil"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["sil"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["sil"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("sil", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["sil"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["lf"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["lf"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["lf"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["lf"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["lf"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["lf"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["lf"].targets.Add((float).0, (float)0.68);
		tracks[8].par.defs.Add("lf", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["lf"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("zh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["zh"].targets.Add((float)-60.0, (float)0.14);
		tracks[2].par.defs.Add("zh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["zh"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("zh", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["zh"].targets.Add((float)-40.0, (float)0.16);
		tracks[4].par.defs.Add("zh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["zh"].targets.Add((float)-20.0, (float)0.02);
		tracks[7].par.defs.Add("zh", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["zh"].targets.Add((float)-50.0, (float)0.96);
		tracks[8].par.defs.Add("zh", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["zh"].targets.Add((float)-50.0, (float)0.30);
		tracks[0].par.defs.Add("sh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["sh"].targets.Add((float)-60.0, (float)0.14);
		tracks[2].par.defs.Add("sh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["sh"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("sh", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["sh"].targets.Add((float)-40.0, (float)0.16);
		tracks[4].par.defs.Add("sh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["sh"].targets.Add((float)-20.0, (float)0.02);
		tracks[7].par.defs.Add("sh", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["sh"].targets.Add((float)-50.0, (float)0.96);
		tracks[8].par.defs.Add("sh", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["sh"].targets.Add((float)-50.0, (float)0.30);
		tracks[0].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["eh"].targets.Add((float)-70.0, (float)0.26);
		tracks[2].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["eh"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["eh"].targets.Add((float)-50.0, (float)0.07);
		tracks[4].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["eh"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["eh"].targets.Add((float)0.0, (float)0.02);
		tracks[6].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["eh"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["eh"].targets.Add((float)-60.0, (float)0.82);
		tracks[8].par.defs.Add("eh", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["eh"].targets.Add((float)-50.0, (float)0.00);
		tracks[0].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["{"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["{"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["{"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["{"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["{"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["{"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["{"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("{", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["{"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("th", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["th"].targets.Add((float)-70.0, (float)0.21);
		tracks[2].par.defs.Add("th", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["th"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("th", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["th"].targets.Add((float)-30.0, (float)0.00);
		tracks[5].par.defs.Add("th", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["th"].targets.Add((float)-60.0, (float)1.01);
		tracks[5].par.defs["th"].targets.Add((float)0.0, (float)1.01);
		tracks[6].par.defs.Add("th", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["th"].targets.Add((float)-50.0, (float)0.70);
		tracks[0].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["}"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["}"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["}"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["}"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["}"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["}"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["}"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("}", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["}"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["?"].targets.Add((float)0.0, (float)0.09);
		tracks[2].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["?"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["?"].targets.Add((float)0.0, (float)0.00);
		tracks[4].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["?"].targets.Add((float)0.0, (float)0.05);
		tracks[5].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["?"].targets.Add((float)0.0, (float)0.00);
		tracks[6].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["?"].targets.Add((float)0.0, (float)0.50);
		tracks[7].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["?"].targets.Add((float)0.0, (float)0.68);
		tracks[8].par.defs.Add("?", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["?"].targets.Add((float)0.0, (float)0.00);
		tracks[0].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[0].par.defs["er"].targets.Add((float)-70.0, (float)0.30);
		tracks[2].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[2].par.defs["er"].targets.Add((float)0.0, (float)0.00);
		tracks[3].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[3].par.defs["er"].targets.Add((float)-60.0, (float)0.19);
		tracks[4].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[4].par.defs["er"].targets.Add((float)-20.0, (float)0.00);
		tracks[5].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[5].par.defs["er"].targets.Add((float)-20.0, (float)0.66);
		tracks[6].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[6].par.defs["er"].targets.Add((float)0.0, (float)0.00);
		tracks[7].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[7].par.defs["er"].targets.Add((float)-50.0, (float)0.73);
		tracks[8].par.defs.Add("er", new LipSyncData.PhoneDefine());
		tracks[8].par.defs["er"].targets.Add((float)-60.0, (float)0.14);
		
		return tracks;
	}
}
